package UI;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * deteksiMenopause3GUI.java
 *
 * Created on 15 Jun 13, 7:12:58
 */
/**
 *
 * @author Kiky
 */
public class deteksiMenopauseUI extends javax.swing.JFrame {

    /** Creates new form deteksiMenopause3GUI */
    public deteksiMenopauseUI() {
        initComponents();
        warning.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        usia = new javax.swing.JLabel();
        emosiLabil = new javax.swing.JLabel();
        sensitif = new javax.swing.JLabel();
        tidakTeratur = new javax.swing.JLabel();
        usiaYa = new javax.swing.JRadioButton();
        usiaTidak = new javax.swing.JRadioButton();
        emosiLabilYa = new javax.swing.JRadioButton();
        emosiLabilTidak = new javax.swing.JRadioButton();
        sensitifYa = new javax.swing.JRadioButton();
        sensitifTidak = new javax.swing.JRadioButton();
        tidakTeraturYa = new javax.swing.JRadioButton();
        tidakTeraturTidak = new javax.swing.JRadioButton();
        analisa = new javax.swing.JButton();
        warning = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deteksi Menopause");

        usia.setText("Apakah usia pasien 40-50 tahun ke atas?");

        emosiLabil.setText("Apakah keadaan emosi pasien labil?");

        sensitif.setText("Apakah pasien semakin merasa sensitif dengan lingkungan sekitar?");

        tidakTeratur.setText("Apakah siklus haid pasien tidak teratur?");

        usiaYa.setText("Ya");
        usiaYa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usiaYaMouseClicked(evt);
            }
        });

        usiaTidak.setText("Tidak");
        usiaTidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usiaTidakMouseClicked(evt);
            }
        });

        emosiLabilYa.setText("Ya");
        emosiLabilYa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emosiLabilYaMouseClicked(evt);
            }
        });

        emosiLabilTidak.setText("Tidak");
        emosiLabilTidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emosiLabilTidakMouseClicked(evt);
            }
        });

        sensitifYa.setText("Ya");
        sensitifYa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sensitifYaMouseClicked(evt);
            }
        });

        sensitifTidak.setText("Tidak");
        sensitifTidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sensitifTidakMouseClicked(evt);
            }
        });

        tidakTeraturYa.setText("Ya");
        tidakTeraturYa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tidakTeraturYaMouseClicked(evt);
            }
        });

        tidakTeraturTidak.setText("Tidak");
        tidakTeraturTidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tidakTeraturTidakMouseClicked(evt);
            }
        });

        analisa.setText("Analisa");
        analisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analisaMouseClicked(evt);
            }
        });

        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setText("Jawaban pertanyaan tidak boleh ada yang kosong");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usia)
                            .addComponent(emosiLabil)
                            .addComponent(sensitif)
                            .addComponent(tidakTeratur)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usiaYa)
                                .addGap(18, 18, 18)
                                .addComponent(usiaTidak))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emosiLabilYa)
                                .addGap(18, 18, 18)
                                .addComponent(emosiLabilTidak))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sensitifYa)
                                .addGap(18, 18, 18)
                                .addComponent(sensitifTidak))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tidakTeraturYa)
                                .addGap(18, 18, 18)
                                .addComponent(tidakTeraturTidak)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(warning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(analisa)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usiaYa)
                    .addComponent(usiaTidak))
                .addGap(18, 18, 18)
                .addComponent(emosiLabil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emosiLabilYa)
                    .addComponent(emosiLabilTidak))
                .addGap(16, 16, 16)
                .addComponent(sensitif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sensitifYa)
                    .addComponent(sensitifTidak))
                .addGap(18, 18, 18)
                .addComponent(tidakTeratur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidakTeraturYa)
                    .addComponent(tidakTeraturTidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(analisa)
                    .addComponent(warning))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usiaYaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usiaYaMouseClicked
        warning.setVisible(false);
        usiaTidak.setSelected(false);// TODO add your handling code here:
        deteksimenopause.DeteksiMenopause.usia=true;
    }//GEN-LAST:event_usiaYaMouseClicked

    private void usiaTidakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usiaTidakMouseClicked
        warning.setVisible(false);
        usiaYa.setSelected(false);// TODO add your handling code here:
        deteksimenopause.DeteksiMenopause.usia=false;
    }//GEN-LAST:event_usiaTidakMouseClicked

    private void emosiLabilYaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emosiLabilYaMouseClicked
        warning.setVisible(false);
        emosiLabilTidak.setSelected(false);
        deteksimenopause.DeteksiMenopause.emosiLabil=true;// TODO add your handling code here:
    }//GEN-LAST:event_emosiLabilYaMouseClicked

    private void emosiLabilTidakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emosiLabilTidakMouseClicked
        warning.setVisible(false);
        emosiLabilYa.setSelected(false);
        deteksimenopause.DeteksiMenopause.emosiLabil=false;// TODO add your handling code here:
    }//GEN-LAST:event_emosiLabilTidakMouseClicked

    private void sensitifYaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sensitifYaMouseClicked
        warning.setVisible(false);
        sensitifTidak.setSelected(false);
        deteksimenopause.DeteksiMenopause.sensitif=true;// TODO add your handling code here:
    }//GEN-LAST:event_sensitifYaMouseClicked

    private void sensitifTidakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sensitifTidakMouseClicked
        warning.setVisible(false);
        sensitifYa.setSelected(false);
        deteksimenopause.DeteksiMenopause.sensitif=false;// TODO add your handling code here:
    }//GEN-LAST:event_sensitifTidakMouseClicked

    private void tidakTeraturYaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidakTeraturYaMouseClicked
        warning.setVisible(false);
        tidakTeraturTidak.setSelected(false);
        deteksimenopause.DeteksiMenopause.tidakTeratur=true;// TODO add your handling code here:
    }//GEN-LAST:event_tidakTeraturYaMouseClicked

    private void tidakTeraturTidakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidakTeraturTidakMouseClicked
        warning.setVisible(false);
        tidakTeraturYa.setSelected(false);
        deteksimenopause.DeteksiMenopause.tidakTeratur=false;// TODO add your handling code here:
    }//GEN-LAST:event_tidakTeraturTidakMouseClicked

    private void analisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analisaMouseClicked
        boolean error=false;
        if (usiaYa.isSelected()==false&&usiaTidak.isSelected()==false)
            error=true;
        else if (sensitifYa.isSelected()==false&&sensitifTidak.isSelected()==false)
            error=true;
        else if (emosiLabilYa.isSelected()==false&&emosiLabilTidak.isSelected()==false)
            error=true;
        else if (tidakTeraturYa.isSelected()==false&&tidakTeraturTidak.isSelected()==false)
            error=true;
        if (error==true){
            warning.setVisible(true);
        }
        else
            deteksimenopause.DeteksiMenopause.analisaMenopause();// TODO add your handling code here:
    }//GEN-LAST:event_analisaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new deteksiMenopauseUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analisa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel emosiLabil;
    private javax.swing.JRadioButton emosiLabilTidak;
    private javax.swing.JRadioButton emosiLabilYa;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel sensitif;
    private javax.swing.JRadioButton sensitifTidak;
    private javax.swing.JRadioButton sensitifYa;
    private javax.swing.JLabel tidakTeratur;
    private javax.swing.JRadioButton tidakTeraturTidak;
    private javax.swing.JRadioButton tidakTeraturYa;
    private javax.swing.JLabel usia;
    private javax.swing.JRadioButton usiaTidak;
    private javax.swing.JRadioButton usiaYa;
    private static javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
